export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export const GET_LIST_BANK = 'GET_LIST_BANK'

export const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT'

export const GET_LIST_CATEGORY = 'GET_LIST_CATEGORY'

export const SAVE_CART = 'SAVE_CART'

export const LOGIN = 'LOGIN'

export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT'

export const ORDER_PRODUCT = 'ORDER_PRODUCT'

export const GET_LIST_PRODUCT_ADMIN = 'GET_LIST_PRODUCT_ADMIN'

export const GET_ORDER_PRODUCT_ADMIN = 'GET_ORDER_PRODUCT_ADMIN'
